spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: api-authentication
                  uri: lb://api-authentication
                  predicates:
                    - Path=/api/v1/login,/api/v1/user
                - id: api-execution
                  uri: lb://api-execution
                  predicates:
                      - Path=/api/v1/script/run/**,/api/v1/language/**
                  filters:
                      - AuthorizedFilter
                - id: api-script
                  uri: lb://api-script
                  predicates:
                    - Path=/api/v1/script/**
                  filters:
                    - AuthorizedFilter
                - id: service-synchronization
                  uri: lb://service-synchronization
                  predicates:
                    - Path=/service/v1/**
    main:
        allow-bean-definition-overriding: true
server:
    port: 8084
eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_SERVER_ADDRESS:localhost}:8761/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        prefer-ip-address: true
        ip-address: ${GATEWAY_ADDRESS:localhost}
        instance-id: ${GATEWAY_ADDRESS:localhost}:8084

application:
    jwt:
        key: ${JWT_KEY:cSK8+%tbKMqT!bsj/@?6vu;AZY#mFCWeY_NbKk0%@*umud1O23#a0n_&S_XIkeE}
        expiration: ${JWT_EXPIRATION:86400000}