spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: api-authentication
                  uri: lb://api-authentication
                  predicates:
                    - Path=/api/v1/user/**
                    - Path=/api/v1/login
    main:
        allow-bean-definition-overriding: true
server:
    port: 8084
eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_SERVER_ADDRESS:localhost}:8761/eureka
        fetch-registry: true
        register-with-eureka: true
application:
    jwt:
        key: ${JWT_KEY:cSK8+%tbKMqT!bsj/@?6vu;AZY#mFCWeY_NbKk0%@*umud1O23#a0n_&S_XIkeE}
        expiration: ${JWT_EXPIRATION:86400000}