spring:
    application:
        name: api-script
    datasource:
        url: ${SCRIPT_DB_URL:jdbc:postgresql://localhost:5432/scriptdb}
        username: ${SCRIPT_DB_USERNAME:postgres}
        password: ${SCRIPT_DB_PASSWORD:postgres}
        driver-class-name: ${SCRIPT_DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
    jpa:
        hibernate:
            ddl-auto: ${SCRIPT_DB_DDL_AUTO:update}
server:
    port: 8081
eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_SERVER_ADDRESS:localhost}:8761/eureka
        fetch-registry: true
        register-with-eureka: true