name: CI

on: [pull_request]

env:
    JAVA_VERSION: '17'
    JAVA_DISTRIBUTION: 'temurin'

jobs:
    checkTests:
        runs-on: ubuntu-latest
        services:
            applicationdb:
                image: postgres:alpine
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: testdb
                ports:
                    - 5432:5432

        steps:
            # SETUP
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  java-version: ${{ env.JAVA_VERSION }}
                  distribution: ${{ env.JAVA_DISTRIBUTION }}
            - uses: actions/cache@v1
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: |
                    ${{ runner.os }}-maven-
            # RUN TESTS
            - name: Run tests
              id: runTests
              run: mvn clean test
              env:
                    AUTHENTICATION_DB_URL: jdbc:postgresql://localhost:5432/testdb
                    AUTHENTICATION_DB_USERNAME: postgres
                    AUTHENTICATION_DB_PASSWORD: postgres
                    AUTHENTICATION_DB_DRIVER_CLASS_NAME: org.postgresql.Driver
                    AUTHENTICATION_DB_DDL_AUTO: create-drop
                    SCRIPT_DB_URL: jdbc:postgresql://localhost:5432/testdb
                    SCRIPT_DB_USERNAME: postgres
                    SCRIPT_DB_PASSWORD: postgres
                    SCRIPT_DB_DRIVER_CLASS_NAME: org.postgresql.Driver
                    SCRIPT_DB_DDL_AUTO: create-drop
            # MESSAGE
            -   name: Send OK Discord Message
                uses: rjstone/discord-webhook-notify@v1
                if: ${{ success() }}
                with:
                    severity: info
                    details: |
                        **Tests ✅**
                    webhookUrl: ${{secrets.DISCORD_URL}}
            -   name: Send Error Discord Message
                uses: rjstone/discord-webhook-notify@v1
                if: ${{ failure() }}
                with:
                    severity: error
                    details: |
                        **Tests ❌**
                    webhookUrl: ${{secrets.DISCORD_URL}}